In [1]:
import pandas as pd

In [2]:
# train이라는 데이터프레임으로 train.csv를 불러오면서 PassengerId를 index로 만들기
train=pd.read_csv("../Data/train.csv", index_col="PassengerId")
# train.set_index("PassengerId", inplace=True)
train.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
train.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [4]:
train.shape

(891, 11)

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [6]:
train.loc[:,['Sex', 'Pclass', 'Survived']].head()

                Sex  Pclass  Survived
PassengerId
1              male       3         0
2            female       1         1
3            female       3         1
4            female       1         1
5              male       3         0

In [7]:
train.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       882, 883, 884, 885, 886, 887, 888, 889, 890, 891],
      dtype='int64', name='PassengerId', length=891)

In [8]:
train.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
# PassengerId가 1번부터 3번까지 데이터 추출
train.loc[1:3,:]
train.iloc[:2+1,:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
# PassengerId가 1, 3, 7, 13만 추출하기
train.loc[[1,3,7,13],:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [11]:
# PassengerId가 1, 3, 7, 13의 정보중 Pclass, Sex, Survived 컬럼 만 추출하기
train.loc[[1,3,7,13],['Pclass','Sex','Survived']]

             Pclass     Sex  Survived
PassengerId
1                 3    male         0
3                 3  female         1
7                 1    male         0
13                3    male         0

----
#### Boolean Indexing

In [12]:
# 성별이 남자인 데이터만 가져와서 5개만 출력하기
train[train.Sex == 'male'].iloc[:5,:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [13]:
# 운임(Fare)이 20달러 이상인 데이터 10개중 PassengerId가 2, 7번 추출하기
train[train.Fare >= 20].head(10).loc[[2,7],:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S

In [14]:
# 운임(Fare)이 20달러 이상인 데이터 갯수?
len(train[train.Fare >= 20])

376

In [15]:
# 운임이 운임의 평균이상인 데이터의 갯수 구하기 
len(train[train.Fare >= train.Fare.mean()])

211

In [16]:
# 운임이 운임의 평균 이상이고 성별이 female인 데이터의 갯수 
len(train[(train.Fare >= train.Fare.mean()) & (train.Sex == 'female')])

104

In [17]:
train.Pclass.unique()

array([3, 1, 2])

In [18]:
# 등급(Pclass)이 1,2,3등급에 탑승인원 ?
for i in range(1,3+1):
    print(f"{i}등급 : {len(train[train.Pclass == i])}")

1등급 : 216
2등급 : 184
3등급 : 491

In [19]:
# 등급(Pclass)이 1,2,3등급에 탑승인원들의 전체 Fare의 합은 ?

for i in range(1,3+1):
    print(f"{i}등급의 운임합 :{train[train.Pclass == i].Fare.sum():10.4f}")

1등급의 운임합 :18177.4125
2등급의 운임합 : 3801.8417
3등급의 운임합 : 6714.6951

In [20]:
train.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [21]:
# 몇명의 여성이 C항구(Embarked)에서 승선 하였는가?
len(train[(train.Embarked == 'C') & (train.Sex == 'female')])

73

In [22]:
# C항구의 전체 탑승인원?
len(train[train.Embarked == 'C'])

168

In [27]:
# 탑승항구가 C항구가 아닌 데이터의 갯수
len(train[train.Embarked != 'C'])

723